fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: check-json
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: pretty-format-json
      args:
        - "--autofix"
    - id: mixed-line-ending
    - id: requirements-txt-fixer
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.221'
  hooks:
    - id: ruff
      # Respect `exclude` and `extend-exclude` settings.
      args: ["--force-exclude"]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.991'
  hooks:
    - id: mypy
